# Generated by Django 3.1.3 on 2021-10-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_customer',
            name='permission',
            field=models.BooleanField(max_length=30, null=True),
        ),
    ]
