# Generated by Django 3.1.3 on 2021-10-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0003_auto_20211004_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_customer',
            name='amt_withdraw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankcustomer.withdrawl'),
        ),
    ]
