# Generated by Django 3.1.3 on 2021-10-07 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='present_banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_due_amt_curr', models.CharField(max_length=30)),
                ('b_balance', models.CharField(max_length=30)),
                ('b_saving_monthly', models.CharField(max_length=30)),
                ('b_total_savings', models.CharField(max_length=30)),
                ('b_spend_mon1', models.CharField(max_length=30)),
                ('b_spend_mon2', models.CharField(max_length=30)),
                ('b_spend_mon3', models.CharField(max_length=30)),
                ('b_spend_mon4', models.CharField(max_length=30)),
                ('b_due_amt_fut', models.CharField(max_length=30)),
                ('b_income_fut', models.CharField(max_length=30)),
                ('b_debt_to_inc', models.CharField(max_length=30)),
                ('b_spend_to_save', models.CharField(max_length=30)),
                ('b_spendings_fut', models.CharField(max_length=30)),
                ('b_minimum', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='future_banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_savings_opt', models.CharField(blank=True, max_length=30, null=True)),
                ('b_spend_opt', models.CharField(blank=True, max_length=30, null=True)),
                ('b_risk_score', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_Bank_Id', models.UUIDField(default=uuid.uuid4)),
                ('c_name', models.CharField(max_length=30)),
                ('c_number', models.CharField(max_length=30)),
                ('c_address', models.CharField(max_length=30)),
                ('c_age', models.CharField(max_length=30)),
                ('c_income', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
