# Generated by Django 3.1.3 on 2021-09-30 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('U_Bank_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('c_number', models.CharField(max_length=30)),
                ('c_address', models.CharField(max_length=30)),
                ('c_age', models.CharField(max_length=30)),
                ('c_income', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
