# Generated by Django 3.1.3 on 2021-09-30 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210930_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='id',
            field=models.AutoField(auto_created=True, default=45, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='U_Bank_Id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
