# Generated by Django 3.1.3 on 2021-10-01 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0005_auto_20211001_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='present_banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_due_amt_curr', models.BigIntegerField()),
                ('b_balance', models.BigIntegerField()),
                ('b_spending_monthly', models.BigIntegerField()),
                ('b_saving_monthly', models.BigIntegerField()),
                ('b_total_savings', models.BigIntegerField()),
                ('b_total_debt', models.BigIntegerField()),
                ('b_spend_mon1', models.BigIntegerField()),
                ('b_spend_mon2', models.BigIntegerField()),
                ('b_spend_mon3', models.BigIntegerField()),
                ('b_spend_mon4', models.BigIntegerField()),
                ('b_spend_mon5', models.BigIntegerField()),
                ('b_spend_mon6', models.BigIntegerField()),
                ('b_due_amt_fut', models.BigIntegerField()),
                ('b_income_fut', models.BigIntegerField()),
                ('b_debt_to_inc', models.IntegerField()),
                ('b_income', models.BigIntegerField()),
                ('b_spendings_fut', models.BigIntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='future_banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_savings_opt', models.BigIntegerField()),
                ('b_spend_opt', models.BigIntegerField()),
                ('b_risk_score', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
