# Generated by Django 3.1.3 on 2021-10-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_future_banking_present_banking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present_banking',
            name='b_spend_mon5',
        ),
        migrations.RemoveField(
            model_name='present_banking',
            name='b_spend_mon6',
        ),
        migrations.RemoveField(
            model_name='present_banking',
            name='b_spending_monthly',
        ),
        migrations.RemoveField(
            model_name='present_banking',
            name='b_total_debt',
        ),
        migrations.AddField(
            model_name='present_banking',
            name='b_spend_to_save',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
