# Generated by Django 3.1.3 on 2021-10-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20211003_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='present_banking',
            old_name='b_income',
            new_name='b_minimum',
        ),
    ]
