# Generated by Django 3.1.3 on 2021-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20211007_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present_banking',
            name='b_balance',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_due_amt_curr',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_saving_monthly',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_total_savings',
            field=models.CharField(max_length=30),
        ),
    ]
