# Generated by Django 3.1.3 on 2021-10-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20211007_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future_banking',
            name='b_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='future_banking',
            name='b_savings_opt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='future_banking',
            name='b_spend_opt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
