# Generated by Django 3.1.3 on 2021-10-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20211007_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present_banking',
            name='b_debt_to_inc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_due_amt_fut',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_income_fut',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_minimum',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_spend_mon1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_spend_mon2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_spend_mon3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_spend_mon4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_spend_to_save',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='present_banking',
            name='b_spendings_fut',
            field=models.CharField(max_length=30),
        ),
    ]
